blog/urls.py
from django.conf.urls import patterns, url
from blog import views

urlpatterns = patterns ('',

	#I should rewrite with more intelegent of build-in views 
	url(r'^tag/(?P<tag_pk>\d+)$', views.IndexView.as_view(), name="tag"),
	url(r'^thread/(?P<thread_pk>\d+)$', views.IndexView.as_view(), name="thread"),
	url(r'^$', views.IndexView.as_view(), name="index"),


	
	url(r'^record/(?P<pk>\d+)$', views.record, name="record"),

	url(r'^like$', views.like, name="like"),


)

regenschirm/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'regenschirm.views.home', name='home'),
    # 
    url(r'^blog/', include('blog.urls', namespace="blog")),
    url(r'^admin/', include(admin.site.urls)),
)

blog/models.py
from django.db import models



class Category(models.Model):
	name = models.CharField(max_length=20, unique=True)

	def __str__(self):
		return self.name



class Tag(models.Model):
	name = models.CharField(max_length=20, unique=True)

	def __str__(self):
		return self.name



class Thread(models.Model):
	title = models.CharField(max_length=140)
	description = models.CharField(max_length=140, null=True)
	author = models.CharField(max_length=30, null=True)
	author_email = models.EmailField(null=True)
	date_creation = models.DateTimeField()
	status = (
		('P', 'posted'),
		('C', 'closed'),
	)
	priority = (
		('L', 'low'),
		('M', 'medium'),
		('H', 'high'),
	)
	category = models.ForeignKey(Category)

	def __str__(self):
		return self.title




class Record(models.Model):
	title = models.CharField(max_length=140)
	content = models.TextField()
	author = models.CharField(max_length=30)
	author_email = models.EmailField(null=True)
	date_creation = models.DateTimeField(null=True)
	status = (
		('P', 'posted'),
		('C', 'closed'),
	)
	thread = models.ForeignKey(Thread)
	priority = (
		('L', 'low'),
		('M', 'medium'),
		('H', 'high'),
	)
	tags = models.ManyToManyField(Tag)
	likes = models.IntegerField(default=0)
	dislikes = models.IntegerField(default=0)

	def __str__(self):
		return self.title



class Comment(models.Model):
	text = models.TextField()
	author = models.CharField(max_length=30)
	author_email = models.EmailField(null=True)
	date_creation = models.DateTimeField(auto_now_add=True)
	record = models.ForeignKey(Record)
	likes = models.IntegerField(default=0)
	dislikes = models.IntegerField(default=0)

	def __str__(self):
		return self.text

blog/forms.py
from django import forms

class CommentForm(forms.Form):
	
	author = forms.CharField(label="Author", max_length=30)
	author_email = forms.EmailField()
	text = forms.CharField(label="Comment", widget=forms.Textarea)

blog/views.py
from django.core.urlresolvers import reverse
from django.shortcuts import render
from blog.models import *
from django.views.generic import View, DetailView
from django.http import HttpResponseRedirect, HttpResponse, Http404
from blog.forms import *

# Create your views here.


class IndexView(View):
	template_name = 'blog/index.html'

	def get(self, request, *args, **kwargs):
		
		if kwargs.get("tag_pk"):
			latest_records = Tag.objects.get(pk=int(kwargs["tag_pk"])).record_set.order_by('-date_creation')
		elif kwargs.get("thread_pk"):
			latest_records = Thread.objects.get(pk=kwargs["thread_pk"]).record_set.order_by('-date_creation')
		else:
			latest_records = Record.objects.order_by('-date_creation')
		
		categories = Category.objects.all()
		context = {'latest_records': latest_records, 'categories': categories}
		return render(request, self.template_name, context)



def like(request):
	if request.is_ajax():
		try:
			record_pk = int(request.POST['record_pk'])
			is_like = request.POST['is_like'] == "true"
		except KeyError:
			return HttpResponse('Error')

		record = Record.objects.get(pk=record_pk)
		
		if is_like:
			record.likes = record.likes + 1
			Record.save(record)
			return HttpResponse(record.likes)
		else:
			record.dislikes = record.dislikes + 1
			Record.save(record)
			return HttpResponse(record.dislikes)

	else:
		raise Http404


def record(request, pk):

	if request.method == 'POST':
		form = CommentForm(request.POST)

		if form.is_valid():
			text = form.cleaned_data['text']
			author = form.cleaned_data['author']
			author_email = form.cleaned_data['author_email']
			record = Record.objects.get(pk=pk)
			c = Comment(text=text, author=author, author_email=author_email, record=record)
			c.save()

	else:
		form = CommentForm()

	context = {}
	(context['record'], ) = Record.objects.get(pk=pk),

	context['comments'] = Record.objects.get(pk=pk).comment_set.order_by('-date_creation')
	context['form'] = form
	
	return render(request, 'blog/record.html', context)

blog/templates/blog/base.html
<!DOCTYPE>
<html lang="en">
<head>
	{% load staticfiles %}
	
	<title>{% block title %}Blog{% endblock %}</title>

    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">
</head>

<body>
	
    
    <div class="blog-masthead">
        <div class="container">
            <nav class="blog-nav">
                {% block menu_bar %}
                    <a class="blog-nav-item" href="{% url 'blog:index' %}">Home</a>
                    <a class="blog-nav-item" href="{% url 'blog:index' %}">Blog</a>
                {% endblock %}
            <nav>
        </div>
    </div>

    <div class="container">

        <div class="blog-header">
            <h1 class="blog-title">The Blog</h1>
            <p class="lead blog-description">Blog created with Django and Bootstrap</p>
        </div>
        <div class="content">
            {% block content %}{% endblock %}
        </div>
    </div>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="{% static 'blog/script.js' %}" type="text/javascript"></script>
</body>

</html>

blog/templates/blog/blog_entry.html
{% csrf_token %}
<div class="blog-post" >
	<h1 class="blog-post-title"><a href="{% url 'blog:record' record.id%}">{{record.title}}</a></h2>
	<p class="blog-post-meta">{{record.thread.all}}   {{record.date_creation |date}}</p> <address>{{record.author}}  {{record.author_email}}</address>
	<div class="content">{{record.content|safe}}</div>

	{% for tag in record.tags.all%}
		<a class="btn tag" href="{% url 'blog:tag' tag.pk%}">{{tag.name}}</a>
	{% endfor %}

	
	<div class="btn btn-success btn-sm like" href="{% url 'blog:like' %}" record-id="{{record.pk}}">{{record.likes}}</div>
	<div class="btn btn-danger  btn-sm dislike" href="{% url 'blog:like' %}" record-id="{{record.pk}}">{{record.dislikes}}</div>
</div>

blog/templates/blog/categories.html
{% extends "blog/base.html" %}

{% block content %}

	<h2>Categories</h2>
	<ul>
		{% for category in object_list %}
			<li><a href="#">{{category.name}}</a></li>
		{% endfor %}

	</ul>

{% endblock %}

blog/templates/blog/category.html
{% extends "blog/base.html" %}

{% block content %}

	<h2>Categories</h2>
	<ul>
		{% for category in object_list %}
			<li><a href="#">{{category.name}}</a></li>
		{% endfor %}

	</ul>

{% endblock %}

blog/templates/blog/index.html
{% extends "blog/base.html" %}

{% block content %}

<div class="row">
	<div class="col-sm-2 blog-sidebar">
		<div class="sidebar-module">
			<h4>Categories</h4>
			<ol class="list-unstyled">
				{% for category in categories %}
					<div class="category" ><button class="btn btn-info btn-default">{{category}}</button>
						
							{% for thread in category.thread_set.all %}
								<a href="{% url 'blog:thread' thread.id%}" class="thread">{{thread.title}}</a>
							{% endfor %}
						
					</div>
				{% endfor %}
			</ol>
		</div>


	</div>

	
	<div class="col-sm-9 col-sm-offset-1 blog-main">
	{% for record in latest_records %}	
		{% include "blog/blog_entry.html" %} 
	{% endfor %}
	</div>
</div>


{% endblock %}

blog/templates/blog/record.html
{% extends "blog/base.html" %}

{% block content %}


	{% include "blog/blog_entry.html" %} 

	
	{% for comment in comments %}	
		<div class="container comment" >
			<h3 class="col-sm-offset-2" >{{comment.author}} </h3><p>{{comment.text}}</p>
		</div>
	{% endfor %}
	

	<form action="{% url 'blog:record' record.pk%}" method="POST" role="form">
		{% csrf_token %}
		{{ form.non_field_errors }}
		<div class="col-sm-offset-2 form-group col-sm-4" >
			<p class="text-danger">{{ form.author.errors}}</p>
			<input id="form.author.id_for_label" type="text" name="form.author.name" maxlength="30" placeholder="{{ form.author.label }}" ></input>
		</div>

		<div class="col-sm-offset-2 form-group col-sm-4" >
			<p class="text-danger">{{ form.author_email.errors}}</p>
			<input id="form.author_email.id_for_label" type="text" name="form.author_email.name" maxlength="75" placeholder="{{ form.author_email.label }}" ></input>
		</div>

		<div class="form-group col-sm-12" >
			<p class="text-danger">{{ form.text.errors}}</p>
		
			<textarea id="{{form.text.id_for_label}}" name="{{form.text.name}}" placeholder="{{ form.text.label }}" rows="5"></textarea>
		</div>		
		<div class="form-group  col-sm-12" >
			<input type="submit" class="btn btn-default" value="Add comment">
		</div>
	</form>

{% endblock %}